name: turiba
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ## State Management
  get: ^4.6.5
  ## Local Storage
  get_storage: ^2.0.3
  ## Fonts Styles
  google_fonts: ^3.0.1
  ## Firebase Services
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_storage: ^10.2.18
  ## Show SVG Icons
  flutter_svg: ^1.1.1+1
  ## Loading Animation
  lottie: ^1.3.0
  ## Check Network Connection
  connectivity_plus: ^2.3.5
  ## Login with Google
  google_sign_in: ^5.3.3
  ## Login with Facebook
  flutter_facebook_auth: ^4.3.4+2
  ## Show Toast
  fluttertoast: ^8.0.9
  ## Carousel Slider
  carousel_slider: ^4.1.1
  ## Ratings Star
  flutter_rating_bar: ^4.0.1
  ## Dartz
  dartz: ^0.10.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  bloc: ^8.0.3
  get_it: ^7.2.0
  onboarding: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  open_url: ^2.0.0
  camera: ^0.10.0
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
 

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/dummy/

